[client]
sensor_name = 'SensorName'
debug = true

[api]
root_certificate = 'RootCertificate'
url = 'Url'
allow_insecure = false
# Set size of chunks during data-upload
upload_chunksize_byte = 1000000

[api.auth]
[api.auth.basic]
username = 'Username'
# required for basic authentication
password = 'Password'

# Bearer authentication settings
[api.auth.bearer]
# specifies enabled token sources.
sources = ['body', 'cookies']
# required refresh token
refresh_token = 'Refresh'
# optional access token
access_token = 'Access'
# custom relative url to the bearer refresh endpoint
refresh_endpoint = 'RefreshEndpoint'

# cookie source specific settings
[api.auth.bearer.cookies]
# name of the refresh token cookie sent from the server
refresh_name = 'RefreshTokenName'
# name of the access token cookie sent from the server
access_name = 'AccessTokenName'

# authorization header specific settings
[api.auth.bearer.header]
# changes <Scheme>, results in 'Authorization: <Scheme> <Token>', defaults to Bearer
scheme = 'Scheme'

[jobs]
storage_path = 'StorageDir'
temp_path = 'TempDir'
polling_interval = '10s'

[jobs.iridium]
disabled = true

[jobs.network]
disabled = true
