#!/bin/bash
stderr() { echo "$@" 1>&2; }

function replay_log() {
  filename=$1
  while read -r line; do
    echo "$line"
    sleep 0.05
  done < "$filename"
}

function replay_stderr() {
  filename=$1
  while read -r line; do
    stderr "$line"
    sleep 0.05
  done < "$filename"
}

# Go to the working directory
cd "$(dirname "$0")" || exit

# This program pretends to be iridium-extractor
stderr "$(cat outputs/header.stderr)"
replay_stderr outputs/progress.stderr &
replay_log outputs/progress.stdout